# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4420f8a34befbb430a64b74cd663ceb149b5a7e07889803cb2c69b8d6437e92a25d64474563f44c8357c0733a579f5b074d5a31d35b578ec3205223f844850c2

test:
  secret_key_base: 2d63d64f402b8c16412209af7c070084ef61557370ca368b6b7528412b23a8c5ddcce8ee9991d175524898ae90e0559fd6f7a65876d0e783643d843f3f93faf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
